# Generated by Django 3.0.7 on 2020-08-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.CharField(max_length=100)),
                ('initialPlace', models.CharField(max_length=100)),
                ('endPlace', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('objectBooked', models.CharField(max_length=100)),
            ],
        ),
    ]
