# Generated by Django 3.0.7 on 2020-08-06 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fastlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=120)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=120)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('initialPlace', models.CharField(max_length=100)),
                ('endPlace', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=120)),
                ('len', models.CharField(max_length=120)),
                ('booker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker_user', to='fastlog.BookerUser')),
                ('driver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_user', to='fastlog.DriverUser')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.ManyToManyField(to='fastlog.booking')),
            ],
        ),
    ]
