# Generated by Django 3.0.7 on 2020-08-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastlog', '0002_album_bookeruser_driveruser_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='len',
        ),
        migrations.AddField(
            model_name='driveruser',
            name='car_number',
            field=models.CharField(default='12AA123', max_length=120),
        ),
        migrations.AddField(
            model_name='driveruser',
            name='lat',
            field=models.CharField(default='12,345', max_length=120),
        ),
        migrations.AddField(
            model_name='driveruser',
            name='len',
            field=models.CharField(default='12,345', max_length=120),
        ),
        migrations.AddField(
            model_name='driveruser',
            name='passport_serial',
            field=models.CharField(default='AZE12345', max_length=120),
        ),
    ]
